import assert from "node:assert/strict"
import { existsSync } from "node:fs"
import { mkdir, mkdtemp, readdir, readFile, rm, writeFile } from "node:fs/promises"
import { tmpdir } from "node:os"
import { dirname, join } from "node:path"
import { test } from "node:test"
import { collect } from "./collect"

const MANIFEST_HEADER =
  "// AUTO-GENERATED by JOT — do not edit. Regenerated on every `jot server`, `jot routes` and `jot console`."

async function makeApp(files: readonly string[]): Promise<string> {
  const root = await mkdtemp(join(tmpdir(), "jot-collect-"))
  for (const file of files) {
    await mkdir(dirname(join(root, file)), { recursive: true })
    await writeFile(join(root, file), "")
  }
  return root
}

function readDot(root: string, file: string): Promise<string> {
  return readFile(join(root, ".jot", file), "utf8")
}

function listDot(root: string): Promise<string[]> {
  return readdir(join(root, ".jot"))
}

test("collect writes deterministic .jot files (sorted, posix imports with extension)", async () => {
  const root = await makeApp([
    "config/app.ts",
    "config/routes.ts",
    "config/database.ts",
    "db/schema.ts",
    "app/models/post.ts",
    "app/controllers/home_controller.ts",
    "app/controllers/admin/posts_controller.ts",
    "app/views/layouts/application.tsx",
    "app/views/home/index.tsx",
  ])
  try {
    const result = collect(root)
    assert.equal(result.hasDatabaseConfig, true)
    assert.equal(result.hasSchema, true)
    assert.deepEqual(result.controllers, ["Admin/Posts", "Home"])
    assert.deepEqual(result.views, ["home/index", "layouts/application"])

    assert.equal(
      await readDot(root, "manifest.ts"),
      `${MANIFEST_HEADER}
import { registerControllers, registerViews } from "jot-framework"
import AdminPostsController from "../app/controllers/admin/posts_controller.ts"
import HomeController from "../app/controllers/home_controller.ts"
import homeIndex from "../app/views/home/index.tsx"
import layoutsApplication from "../app/views/layouts/application.tsx"

registerControllers({ "Admin/Posts": AdminPostsController, Home: HomeController })
registerViews({ "home/index": homeIndex, "layouts/application": layoutsApplication })
`,
    )

    assert.equal(
      await readDot(root, "entry.ts"),
      `// AUTO-GENERATED by JOT — do not edit.
import "./manifest.ts"
import { start } from "jot-framework"
import app from "../config/app.ts"
import routes from "../config/routes.ts"
import database from "../config/database.ts"

await start({ app, routes, database })
`,
    )

    assert.equal(await readDot(root, ".gitignore"), "*\n")

    const consoleScript = await readDot(root, "console-script.ts")
    assert.match(consoleScript, /import \* as postNs from "\.\.\/app\/models\/post\.ts"/)
    assert.match(consoleScript, /setDefaultDatabase\(db\)/)
    assert.match(
      consoleScript,
      /startRepl\(\{ prompt: "jot> ", useGlobal: false, ignoreUndefined: true \}\)/,
    )

    const dbScript = await readDot(root, "db-script.ts")
    assert.match(dbScript, /import \* as schemaNs from "\.\.\/db\/schema\.ts"/)
    assert.match(dbScript, /await db\.migrate\(\)/)
  } finally {
    await rm(root, { recursive: true, force: true, maxRetries: 5, retryDelay: 200 })
  }
})

test("collect is idempotent (byte for byte)", async () => {
  const root = await makeApp([
    "config/app.ts",
    "config/routes.ts",
    "config/database.ts",
    "db/schema.ts",
    "app/controllers/home_controller.ts",
    "app/views/home/index.tsx",
  ])
  try {
    collect(root)
    const before = await Promise.all(
      (await listDot(root)).sort().map(async (file) => [file, await readDot(root, file)] as const),
    )
    collect(root)
    const after = await Promise.all(
      (await listDot(root)).sort().map(async (file) => [file, await readDot(root, file)] as const),
    )
    assert.deepEqual(after, before)
  } finally {
    await rm(root, { recursive: true, force: true, maxRetries: 5, retryDelay: 200 })
  }
})

test("without config/database.ts: no database import and no db/console scripts", async () => {
  const root = await makeApp([
    "config/app.ts",
    "config/routes.ts",
    "app/controllers/home_controller.ts",
    "app/views/home/index.tsx",
  ])
  try {
    const result = collect(root)
    assert.equal(result.hasDatabaseConfig, false)
    assert.equal(result.hasSchema, false)
    assert.doesNotMatch(await readDot(root, "entry.ts"), /database/)
    assert.ok(existsSync(join(root, ".jot", "routes-script.ts")))
    assert.ok(!existsSync(join(root, ".jot", "db-script.ts")))
    assert.ok(!existsSync(join(root, ".jot", "console-script.ts")))
  } finally {
    await rm(root, { recursive: true, force: true, maxRetries: 5, retryDelay: 200 })
  }
})

test("stale db/console scripts are removed when config/database.ts disappears", async () => {
  const root = await makeApp([
    "config/app.ts",
    "config/routes.ts",
    "config/database.ts",
    "db/schema.ts",
  ])
  try {
    collect(root)
    assert.ok(existsSync(join(root, ".jot", "db-script.ts")))
    await rm(join(root, "config", "database.ts"))
    collect(root)
    assert.ok(!existsSync(join(root, ".jot", "db-script.ts")))
    assert.ok(!existsSync(join(root, ".jot", "console-script.ts")))
  } finally {
    await rm(root, { recursive: true, force: true, maxRetries: 5, retryDelay: 200 })
  }
})

test("without db/schema.ts the db-script uses an empty schema", async () => {
  const root = await makeApp(["config/app.ts", "config/routes.ts", "config/database.ts"])
  try {
    collect(root)
    const script = await readDot(root, "db-script.ts")
    assert.match(script, /const schema = \{\} as Record<string, unknown>/)
    assert.doesNotMatch(script, /schemaNs/)
  } finally {
    await rm(root, { recursive: true, force: true, maxRetries: 5, retryDelay: 200 })
  }
})

test("missing app/views yields empty registries but a valid manifest", async () => {
  const root = await makeApp([
    "config/app.ts",
    "config/routes.ts",
    "app/controllers/home_controller.ts",
  ])
  try {
    const result = collect(root)
    assert.deepEqual(result.views, [])
    const manifest = await readDot(root, "manifest.ts")
    assert.match(manifest, /registerViews\(\{\}\)/)
    assert.match(manifest, /registerControllers\(\{ Home: HomeController \}\)/)
  } finally {
    await rm(root, { recursive: true, force: true, maxRetries: 5, retryDelay: 200 })
  }
})

test("collect ignores .tsx controllers and dotfiles", async () => {
  const root = await makeApp([
    "config/app.ts",
    "config/routes.ts",
    "app/controllers/home_controller.ts",
    "app/controllers/skip_controller.tsx",
    "app/views/.hidden.tsx",
    "app/views/home/index.tsx",
    "app/views/.cache/ignored.tsx",
  ])
  try {
    const result = collect(root)
    assert.deepEqual(result.controllers, ["Home"])
    assert.deepEqual(result.views, ["home/index"])
  } finally {
    await rm(root, { recursive: true, force: true, maxRetries: 5, retryDelay: 200 })
  }
})
